s  = set() 

n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)
n = int(input("Enter number : "))
s.add(n)

print(s)